name: deen_iq
description: "Deen - Islamic Quiz App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.3
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  flutter_riverpod: ^3.3.1
  cupertino_icons: ^1.0.8

  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0
  flutter_animate: ^4.5.2
  audioplayers: ^6.6.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: DroidNaskh
      fonts:
        - asset: assets/fonts/DroidNaskh.ttf
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1 Ver10.otf

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700